class_name LocalizedText
extends Node

var fallback: Dictionary = {
	"FACTION_DOCK_RATS": "Dock Rats",
	"FACTION_IRON_SERPENTS": "Iron Serpents",
	"FACTION_MERIDIAN_BOYS": "Meridian Boys",
	"FACTION_NORTHSIDE_CREW": "Northside Crew",
	"FACTION_VELVET_CIRCLE": "Velvet Circle",
	"FACTION_GENERIC": "Rival Crew",
	"TRAIT_SCRAPPY": "Scrappy",
	"TRAIT_ARMORED": "Armored",
	"TRAIT_WATCHFUL": "Watchful",
	"TRAIT_AGGRESSIVE": "Aggressive",
	"TRAIT_CONNECTED": "Connected",
	"ENCOUNTER_ROADBLOCK": "Roadblock",
	"ENCOUNTER_SURVEILLANCE": "Surveillance Sweep",
	"ENCOUNTER_CONVOY": "Convoy Ambush",
	"ENCOUNTER_TURF_PUSH": "Turf Push",
	"ACH_FIRST_TURF": "First Territory",
	"ACH_ALL_DISTRICTS": "Citywide",
	"ACH_ALLIANCE_4": "Trusted Crew",
	"ACH_ACCOUNT_7": "Made Boss",
	"ACH_MAX_SAFEHOUSE": "Command Center",
	"ACH_RESOURCE_NETWORK": "Supply Network",
	"ACH_SPECIALISTS_3": "Specialist Crew",
	"ACH_DOMINION": "Concrete Dominion",
	"ACH_DESC_FIRST_TURF": "Capture your first district.",
	"ACH_DESC_ALL_DISTRICTS": "Own every district in the city.",
	"ACH_DESC_ALLIANCE_4": "Reach Crew Support Level 4.",
	"ACH_DESC_ACCOUNT_7": "Reach Account Level 7.",
	"ACH_DESC_MAX_SAFEHOUSE": "Upgrade the Safehouse to Level 5.",
	"ACH_DESC_RESOURCE_NETWORK": "Build both the Scrapyard and Data Hub.",
	"ACH_DESC_SPECIALISTS_3": "Reach Level 3 with Enforcer, Driver, and Spy specialists.",
	"ACH_DESC_DOMINION": "Complete the citywide endgame requirements.",
	"UI_STORE": "Store",
	"UI_STORE_TITLE": "PROTOTYPE STORE",
	"UI_STORE_NOTICE": "Preview only. No real payments are connected. Offers focus on progression speed and resources, not exclusive combat units.",
	"UI_STORE_DISABLED": "Purchases Disabled — Prototype Catalog",
	"UI_STORE_TOOLTIP": "No billing SDK, store receipt validation, or real-money transaction is connected.",
	"UI_INCLUDES": "Includes:",
	"UI_CLOSE": "Close",
	"UI_TERRITORY": "Territory",
	"UI_TERRITORY_TITLE": "TERRITORY COMMAND",
	"UI_TURF_INCOME": "TURF INCOME",
	"UI_DISTRICTS": "DISTRICTS",
	"UI_NEXT_DISCOVERY": "NEXT DISCOVERY",
	"UI_COMMAND_SCAN": "Safehouse Command Scan",
	"UI_RESOURCE_FACILITIES": "RESOURCE FACILITIES",
	"UI_RIVAL_ENCOUNTER": "RIVAL ENCOUNTER",
	"UI_NO_THREAT": "No active threat.",
	"UI_ALLIANCE_TASKS": "CREW OPERATIONS",
	"UI_COLLECT_RESOURCES": "Collect Parts / Intel",
	"UI_REVEAL_INTEL": "Reveal with Intel",
	"UI_CLEAR_PATROL": "Clear Patrol",
	"UI_PROGRESSION": "Progression",
	"UI_ACCOUNT_LEVEL": "ACCOUNT LEVEL",
	"UI_XP": "XP",
	"UI_UNLOCKS_TITLE": "DISTRICT / CITY UNLOCKS",
	"UI_MISSIONS": "MISSIONS",
	"UI_NO_COST": "No cost",
	"UI_ACHIEVEMENTS": "Achievements",
	"UI_ACHIEVEMENTS_TITLE": "ACHIEVEMENTS & ENDGAME",
	"UI_REWARDS": "Rewards",
	"UI_PROFILE": "Profile",
	"UI_AVATAR": "Avatar",
	"UI_CHANGE": "Change",
	"UI_POWER_RATING": "Power Rating",
	"UI_BADGES": "BADGES",
	"UI_INBOX": "INBOX",
	"UI_NO_MESSAGES": "No messages.",
	"UI_CLAIM_ALL": "Claim All Mail Rewards",
	"UI_CLAIMED": "CLAIMED",
	"UI_REWARD_READY": "REWARD READY",
	"UI_EVENT": "EVENT",
	"UI_EVENT_MARKS": "Event Marks",
	"UI_TIME_REMAINING": "Time remaining",
	"UI_TACTICS": "TACTICS",
	"UI_PRE_RAID_PLAN": "PRE-RAID PLAN",
	"UI_RISK_PLAN": "Risk Plan",
	"UI_EQUIPMENT": "Equipment",
	"UI_UPGRADE": "Upgrade",
	"UI_CONSUMABLE": "Consumable",
	"UI_SELECTED_COUNTER": "SELECTED TARGET COUNTER",
	"TUTORIAL_PROGRESS": "TUTORIAL",
	"TUTORIAL_SKIP": "Skip Tutorial",
	"TUTORIAL_START": "Start",
	"TUTORIAL_WELCOME_TITLE": "WELCOME TO CONCRETE DOMINION",
	"TUTORIAL_WELCOME_BODY": "Build a crew, strengthen your base, and take control of the city. This guide follows the core loop without blocking other actions.",
	"TUTORIAL_RECRUIT_TITLE": "BUILD YOUR CREW",
	"TUTORIAL_RECRUIT_BODY": "Open Crew Barracks and complete any recruitment job. Enforcers provide frontline depth; Drivers and Spies are essential crew-support specialists.",
	"TUTORIAL_UPGRADE_TITLE": "STRENGTHEN THE SAFEHOUSE",
	"TUTORIAL_UPGRADE_BODY": "Upgrade the Safehouse once. Higher Safehouse levels improve construction speed, raid Cash, and Command Scan cooldown.",
	"TUTORIAL_WORLD_TITLE": "ENTER THE WORLD MAP",
	"TUTORIAL_WORLD_BODY": "Switch from BASE to WORLD. The World map contains rival districts, raid targets, turf income, fog, and patrol pressure.",
	"TUTORIAL_ALLIANCE_TITLE": "BUILD CREW SUPPORT",
	"TUTORIAL_ALLIANCE_BODY": "Open Crew Support and join a Driver or Spy slot. These are story crew allies, separate from the real-player Faction system.",
	"TUTORIAL_RAID_TITLE": "WIN YOUR FIRST RAID",
	"TUTORIAL_RAID_BODY": "Select a discovered target, preview crew-support damage, and win a raid. Defeated troops recover in the Clinic instead of dying permanently.",
	"TUTORIAL_DONE_TITLE": "CITY LOOP UNLOCKED",
	"TUTORIAL_DONE_BODY": "You know the core loop: build your Family, recruit crew, use story support, raid Rival Families, capture turf, and later join a player Faction.",
	"UI_DOMINION_COMPLETE": "DOMINION COMPLETE — citywide control secured.",
	"UI_DOMINION_REQUIREMENTS": "ENDGAME: own all districts, reach Account Lv.7 + Crew Support Lv.4, max core buildings, and establish all specialist/resource facilities."
}


func text(key: String, replacements: Dictionary = {}) -> String:
	var translated := tr(key)
	var value := translated
	if translated == key:
		value = String(fallback.get(key, key))

	for token in replacements.keys():
		value = value.replace("{%s}" % String(token), String(replacements[token]))
	return value


func has_key(key: String) -> bool:
	return fallback.has(key)
